### POST 프로젝트
POST http://localhost:8082/project
Content-Type: application/json
MEMBER-SERIAL-ID: 1

{
  "name": "Project10",
  "projectStatusId": 1
}

### GET 프로젝트 리스트
GET http://localhost:8082/project
MEMBER-SERIAL-ID: 1

### GET 프로젝트
GET http://localhost:8082/project/1
MEMBER-SERIAL-ID: 1

### PUT 프로젝트
PUT http://localhost:8082/project
Content-Type: application/json
MEMBER-SERIAL-ID: 1

{
  "id": 1,
  "name": "Updated",
  "projectStatusId": 2
}

### DELETE 프로젝트
DELETE http://localhost:8082/project/10
MEMBER-SERIAL-ID: 1

### POST 프로젝트멤버
POST http://localhost:8082/project/member
Content-Type: application/json
MEMBER-SERIAL-ID: 2

{
  "projectId": 2,
  "memberId": 3
}

### GET 프로젝트멤버 리스트
GET http://localhost:8082/project/2/member
MEMBER-SERIAL-ID: 2

### DELETE 프로젝트멤버
DELETE http://localhost:8082/project/member
Content-Type: application/json
MEMBER-SERIAL-ID: 1

{
  "projectId": 1,
  "memberId": 4
}