### POST 프로젝트
POST http://localhost:8082/project
Content-Type: application/json
MEMBER-SERIAL-ID: 2

{
  "name": "New Project",
  "projectStatusId": 1
}

### GET 프로젝트 리스트
GET http://localhost:8082/project
MEMBER-SERIAL-ID: 1

### GET 프로젝트
GET http://localhost:8082/project/26
MEMBER-SERIAL-ID: 1

### PUT 프로젝트
PUT http://localhost:8082/project
Content-Type: application/json
MEMBER-SERIAL-ID: 1

{
  "id": 26,
  "name": "Updated Project Name",
  "projectStatusId": 2
}

### DELETE 프로젝트
DELETE http://localhost:8082/project/28
MEMBER-SERIAL-ID: 1

### POST 프로젝트멤버
POST http://localhost:8082/project/member
Content-Type: application/json
MEMBER-SERIAL-ID: 1

{
  "projectId": 28,
  "memberId": 2
}

### DELETE 프로젝트멤버
DELETE http://localhost:8082/project/member
Content-Type: application/json
MEMBER-SERIAL-ID: 1

{
  "projectId": 29,
  "memberId": 2
}